# Generated by Django 2.2 on 2020-09-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='send_email',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='send_email',
            old_name='email',
            new_name='for_send_email',
        ),
    ]
